ast_ES:
  bridge:
    description: Munches estraes nes fasteres fora de les villes dibúxense apriesa y ensin mirar si crucen ríos o regatos. Alcuentra un llugar onde un mapeador escaeció partir una estrada y marcar una ponte, y faelo tu.
    title: Dibuxa una ponte
  stream:
    description: Los ríos del mundu de vezu tán nel mapa, pero hai una bayura de regatos que non. Escueyi unu, y fai el mapa. Non un ríu — un regatu.
    title: Dibuxa un regatu
  postcode:
    description: En dellos paises, como Rusia o los EEXX, puedes buscar un códigu postal nuna base de datos disponible de mou públicu. N'otros puedes sabelo o deducilo de fontes indireutes, como la páxina web d'una tienda. Alcuentra'l códigu postal de cualquier edificiu que nun lu tenga, y ponlu nel mapa.
    title: Amiesta un códigu postal
  turn_restriction:
    description: Alcuentra una torga de xiru que nun tea nel mapa en Mapillary o otra fonte compatible con OSM. Si quiés, escueyi una villa más pequeña. Pon la torga nel mapa.
    title: Amiesta una torga de xiru
  osmand:
    description: '[https://play.google.com/store/apps/details?id=net.osmand OsmAnd] ye una de les aplicaciones populares d''OpenStreetMap pa preseos Android, configurable enforma, pero una migayina complicáu pa dalgunes persones. Puede xubir puntos al mapa. Instala''l complementu «OSM Editing» y crea un puntu auquiera. Llei [http://osmand.net/features?id=osm-editing-plugin la documentación] si te pierdes na interfaz.'
    title: Usar OsmAnd
  improve_river:
    description: "Bona parte de los ríos yá tán nel mapa. El problema ye qu'esto ta fecho usando imaxes de satélite de baxa resolución. Agora puedes ameyoralo: llanza JOSM, seleiciona un ríu, prime «W» y ameyora la vía. Amiesta polo menos 10 nodos a un ''waterway=river''."
    title: Ameyorar un ríu
  josm:
    description: "Instala l'editor JOSM, si nun lo ficisti yá, y edita daqué con él. Recomendamos dibuxar dellos edificios:\n \nDescarga parte del mapa, añade una capa d'imaxe, prime «A» y fai click na esquina d'un edificiu. Darréu fai doble-click nuna esquina axacente corner, pa crear una llinia. Entós prime «X» y arrastra la llinia pa tresformala nun rectángulu. P'acabar, prime «Alt+A» p'añadir ''building=yes'', y xube'l cambiu."
    title: Fai una edición con JOSM
  fix:
    description: 'Los comentarios de los conxuntos de cambios son importantes. Pero güei ye más fácil pa ti: fai un cambiu y pon «fix» nel campu de comentariu de los cambios. Sólo eses trés lletres, nada más.'
    title: Una pequeña igua
  gomap:
    description: 'Mentanto que la plataforma Android tien munchos editores pa OSM, pa iOS falten. El meyor editor pa OSM d''ellos venía siendo [https://itunes.apple.com/app/id592990211 Go Map!!] (colos signos d''esclamación), pero l''últimu anovamientu foi en 2015. Sicasí, funciona: pruébalu, fai una edición con él.'
    title: Go Map!!!
  giveway:
    description: Hai una etiqueta especial pa marcar el triángulu de la señal «dexe pasu» nel mapa. Ye [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way highway=give_way], naturalmente. Alcuentra esa señal, o usando Mapillary o de memoria, pon un nodiu na estrada que tien de dexar pasar, y marca esi nodiu cola etiqueta. Añade tamién una etiqueta priority_road a la estrada con preferencia.
    title: Dexe'l pasu
  note:
    description: Activa les notes nel sitiu web d'OSM y alcuentra una nota ensin resolver que puedas iguar. Marca la nota como resuelta.
    title: Resuelve una nota
  around_the_world:
    description: Vamos crear un conxuntu de cambios con un cuadru de llende xigante. Primero dibuxa daqué nel [https://www.openstreetmap.org/#map=5/-48.487/-69.895 Sur de Chile], Y llueu en [https://www.openstreetmap.org/#map=6/55.912/159.335 Kamchatka].
    title: Alredor del mundu en cinco minutos
  railway:
    description: De vezu los ferrocarriles reciben menos atención que les estraes, ¡dibuxa dalgún, nun son menos importantes! Por casu, alcuentra una estación y amiesta les víes d'apartaderu que falten.
    title: Dibuxa un ferrocarril
  highway:
    description: De vezu esta ye la primera cosa que fai la xente al xunise a OpenStreetMap. Alcuentra una estrada cercaba que nun tea nel mapa y añádela.
    title: Pon una estrada nel mapa
  subway:
    description: Pa esto necesites conocer l'[https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping esquema de Tresporte Públicu v2]. Visita'l [https://osmz.ru/subways/ Validador de metro] y escueye una ciudá con un error nel metro. Tendría d'implicar tresformar una ruta de metro. Igua'l fallu (y puedes dexalo equí, o siguir llimpiando la rede).
    title: Igua un metro
  sidewalk:
    description: Una cera ye un camín cabo una estrada. Pa un meyor enrutamientu de peatones, alcuentra una estrada ensin cera nel mapa, y dibuxa un camín a cada llau (comprobando con una imaxe) y amiesta una etiqueta ''footway=sidewalk''. Ci amiestes un pasu de peatones como camín, usa ''highway=footway + footway=crossing''.
    title: Amiesta una cera
