ja:
  bridge:
    description: 郊外にざっくりと描かれた多くの道路は、水路や川との交差を処理しわすれていることがしばしばあります。そうした場所を見つけ、道路ウェイを分割して橋を適切に追加しましょう。
    title: 橋を描こう
  stream:
    title: 小さな川を描こう
  osmand:
    description: '[https://play.google.com/store/apps/details?id=net.osmand OsmAnd] はAndroid端末でよく使われるOpenStreetMapアプリのひとつです。細かい箇所までカスタマイズできるのが特徴ですが、人によっては複雑すぎるかもしれません。OsmAndではマップにポイントを投稿することができます。 "OSM Editing"プラグインをインストールして、どこかにポイントを作成しましょう。操作方法については [http://osmand.net/features?id=osm-editing-plugin the documentation] に解説があります。'
    title: OsmAndを使おう
  improve_river:
    description: "ほとんどの大きな河川は既に描かれています。問題は、それらが描かれる際に、画質の悪い衛星写真が利用されている、ということです。いまの私たちならもっと正確に描くことが可能です。JOSMを起動し、河川を選択し、 \"W\"キーを押してウェイの精度を向上させましょう。\"waterway=river\"ウェイに対して、10個以上のノードを追加してください。"
    title: 河川の品質向上
  josm:
    description: "未体験のかたもJOSMをインストールし、JOSMで何かを描いてみましょう。対象は建物がオススメです。\n\nマップデータをダウンロードし、背景となる写真レイヤを追加し、\"A\"キーを押して建物のどこかの角をクリックします。次に、その近くの別の角をダブルクリックし、線を作ります。その後、”X”キーを押して、いま描いた線を四角形にします。最後に、\"Alt+A\"を押して、\"building=yes\"タグを追加し、変更点をアップロードしましょう。"
    title: JOSMを使ってみよう
  fix:
    description: '変更セットのコメントは本来非常に重要です。ですが、今日のあなたには関係ありません。地図の編集を行い、コメントとして単に "fix" とだけ入力しましょう。入力するのはこの3文字だけで、それ以上入れてはいけません。'
    title: 小さな変更
  gomap:
    description: 'Androidプラットフォームには多くのOSMエディタが用意されていますが、iOSではまだ少ないのが現状です。そのなかで最も使いやすいアプリは  [https://itunes.apple.com/app/id592990211 Go Map!!] （ビックリマークまでを含む）なのですが、更新が2015年で止まっています。ともあれ、少なくとも動作はします。このアプリを使って編集をしてみましょう。'
    title: Go Map!!!
  note:
    description: OSMウェブサイトで地図メモ（notes）機能を有効化して、対応可能なメモを解決済みにしましょう。
    title: 地図メモ (note) の解決
  around_the_world:
    title: 5分で巡る世界旅行
  highway:
    description: 道路は、OpenStreetMapに参加するひとの多くがはじめて地図に描く地物です。近くにある描かれていない道路を探して、描いてみましょう。
    title: 道路を描こう
  buildings:
    description: 場所はどこでもよいので、建物を20個描きましょう。お好みのエディタを起動し、まだあまり描かれていない郊外や工業地区を探して建物を描きましょう。
  railway:
    description: 道路に比べて興味を持たれることの少ない鉄道路線、ですが、重要さは道路に負けません！ 今日は路線情報をマップしましょう。例えば、駅の近くにあるサイドトラックがまだ描けるかもしれません。
    title: 鉄道を描こう
  sidewalk:
    description: ここでの歩道(sidewalk)とは、道路に接して存在する歩行者用の歩道を指します。歩行者用の経路検索のため、歩道が描かれていない道路を探して、その両脇に1本ずつ、 (航空写真を参考に) 歩道を描いて、追加で"footway=sidewalk"タグをつけましょう。横断歩道をウェイとして描く場合は、''highway=footway + footway=crossing'を使ってください。
    title: 歩道を描こう
