ru:
  bridge:
    description: Многие дороги в сельской местности рисуют небрежно и без учета пересечения ручьев и рек. Найдите место, где картографы забыли разделить дорогу и отметить мост, и сделайте это за них.
    title: Протяните мост
  stream:
    description: Реки в основном отмечены по всему миру, но вот ручьев слишком много. Выберите любой и нанесите его на карту. Не реку — ручей.
    title: Нарисуйте ручей
  sidewalk:
    title: Добавьте тротуар
  osmand:
    description: '[https://play.google.com/store/apps/details?id=net.osmand OsmAnd] — одно из самых популярных приложений, использующих OpenStreetMap, гибкое в настройке, но оно может показаться сложным в освоение. С помощью него можно добавлять точечные объекты. Установите плагин "Редактирование OSM" и создайте точечный объект. Если возникли сложности, прочитайте [http://osmand.net/features?id=osm-editing-plugin the documentation].'
    title: Используйте OsmAnd
  improve_river:
    description: "Большинство рек уже нанесено на карту. Проблема лишь в том, что это было сделано с использованием снимков с низким разрешением. Настало время исправить это: сдуйте пыль с JOSM, выберите реку, нажмите \"W\" и начинайте уточнять геометрию реки. Добавьте минимум 10 новых точек к ''waterway=river''."
    title: Уточните реку
  josm:
    description: "Установите редактор JOSM, если ещё не сделали это, и отредактируйте им что-нибудь. Мы советуем порисовать домики:\n\nСкачайте область карты, добавьте слой снимков, нажмите «A» и щёлкните на углу здания. Затем дважды щёлкните на соседнем углу, чтобы получилась линия. Потом нажмите «X» и вытяните линию в прямоугольник. Наконец, нажмите «Alt+A» и добавьте тег ''building=yes''. Готово — отправляйте изменения."
    title: Используйте JOSM
  fix:
    description: 'Комментарии к изменениям важны. Но не для вас сегодня: внесите изменения и напишите «исправление» в поле комментария. Только это слово, ничего другого.'
    title: Малая правка
  gomap:
    description: 'Пока Android изобилует приложениями для редакторавания OSM, iOS страдает от их отсутствия. Лучший редактор под iOS это [https://itunes.apple.com/app/id592990211 Go Map!!] (с двумя восклицательными знаками), который не обновляется с 2015. Но всё ещё работает исправно: дайте ему шанс, воспользуйтесь им и сделайте в нём правку.'
    title: Go Map!!!
  giveway:
    description: Существует специальный тег для того, чтобы обозначить знак "уступи дорогу" — [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way highway=give_way]. Найдите такой знак, при помощи Mapillary или по памяти, разместите точку на дороге,  двигаясь по которой, нужно уступить транспорту с главной дороги, и укажите соответствующий тег. Также добавьте тег priority_road=* главной дороге.
    title: Уступите дорогу
  note:
    description: Включите заметки на сайте OSM и найдите нерешенные заметки, которые вы можете исправить. Исправьте заметку
    title: Закройте заметку
  highway:
    description: Часто это первое, что люди делают после регистрации в OpenStreetMap. Найдите неотрисованную дорогу поблизости и добавьте её на карту.
    title: Проложите дорогу
  subway:
    description: Если вы уверены в себе, ознакомьтесь с [https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping Public Transport v2 schema]. Откройте [https://osmz.ru/subways/ Subway Validator] и выберите город, в котором нашлись ошибки. Исправление должно затрагивать маршруты метрополитена. Исправьте — и будьте таковым, или продолжайте вычищать ошибки сети метрополитенов.
    title: Почините метро
  buildings:
    description: Нарисуйте хотя бы 20 зданий. Откройте свой редактор, скачайте плохо отрисованную местность в деревне или промзоне, и пообклацывайте здания.
    title: Обведите двадцать зданий
  lanes:
    description: Найдите дороге без тега ''lanes''. Подключите детальные снимки для этой местности и укажите дороге количество полос.
    title: Сосчитайте полосы
  leaf_types:
    description: Посадить дерево — это не просто отметить его тегом "natural=tree_node". Вам нужно также указать его тип. Пожалуйста прочтите на вики страницы [https://wiki.openstreetmap.org/wiki/RU:Key:leaf_type leaf_type] и [https://wiki.openstreetmap.org/wiki/RU:Key:leaf_cycle leaf_cycle], а после, используя эти теги, добавьте на карты 2 дерева, расположенные недалеко от вашего дома или в знакомом вам месте.
    title: Посадите два дерева
  tiger:
    description: '[https://wiki.openstreetmap.org/wiki/TIGER TIGER] — общедоступный набор данных о дорогах в США. Он был импортирован в 2005, и импорт не был идеальным. Отыщите дороги с tiger:reviewed=no и исправьте хотя бы три, указав верный класс дороги и убирая тег tiger:reviewed=no.'
    title: Причешите Tiger
  tracks:
    description: Дороги сельскохозяйственного назначения, лесотехнические и лесозаготовительные дороги, не ведущие к жилым или промышленным объектам. Такие отмечаются [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack highway=track] с дополнительным ''tracktype=gradeN'', где N от 1 (лучшее качество дороги) до 5 (худшее качество дороги). Возьмите поле или лес и отрисуйте 2-3 километра такой дороги.
    title: Порисуйте грунтовки
  coastline:
    description: Почти всю береговую линию импортировали давным-давно из векторизованных снимков низкого разрешения. Вам будет несложно уточнить её в паре мест. Добавьте минимум 10 точек в линии ''natural=coastline''.
    title: Уточните береговую линию
  turn_restriction:
    description: Отыщите неотмеченный запрет на манёвр при помощи Mapillary или любого другого доступного для OSM источника данных. Сделайте это в небольшом городке, если желаете. Отметьте запрет.
    title: Добавьте запрет поворота
  postcode:
    description: В некоторыех странах, таких как Россия или США, почтовый индекс можно узнать при помощи общедоступной базы данных. В других же — либо вы его знаете, либо вам придётся разузнать его из косвенных источников, например на веб-сайте магазина. Узнайте почтовый индекс любого здания, где он отсутствует, и укажите его.
    title: Добавьте почтовые индексы
  railway:
    description: Железные дорогие получают меньше внимание чем автомобильные — отрисуйте несколько, они не менее важны. Например, найдите станцию и добавьте отсутствующие пути.
    title: Отрисуйте железную дорогу
  turnlanes:
    description: Ознакомьтесь с [https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane turn:lanes], найдите перекрёсток, на котором видна дорожная разметка (спутниковые снимки и Mapillary в помощь), разметьте все полосы для поворота на всех (обычно 4) дорогах перекрёстка.
    title: Движение по полосам
  hot_task:
    description: 'Откройте [https://tasks.hotosm.org/ HOT Tasking Manager] и выберите любое доступное задание. Затем выберите любой желтый желтый прямоугольний и провалидируйте его. Понаблюдайте, как новички обрисовывают здания. Помедитируйте на это. А затем исправьте неточности: выпрямите углы, скорректируйте форму здания. Пары домов будет достаточно.'
    title: Поправьте здания
  mapsme:
    description: MAPS.ME — это не только карты и навигатор. При помощи него вы можете также совершать правки. Отредактируйте что-то, что уже на карте. Или добавьте то, чего на ней ещё нет, нажав на "Добавить место на карту" во всплывающем меню.
    title: Попробуйте MAPS.ME
  streetcomplete:
    description: Если у вас iPhone, то это провал. Пользователям Android следует установить [https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete StreetComplete] и выполнить несколько заданий в нём. Они не займут у вас больше секунды времени.
    title: Используйте StreetComplete
  delete:
    description: Отыскать что-то на карте не так уж сложно. Но сможете ли вы найти что-нибудь, что пора удалить? Удалите 5 объектов, но только такие, которые устарели или утратили свою актуальность и не подлежат исправлению.
    title: Удалить!
